spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}

server:
  port: 7090
  servlet:
    context-path: /auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

keycloak:
  realm: recommendation-music
  domain: keycloak.emamagic.com
  adminClientId: admin-cli
  adminClientSercret: my-sercret
  client: authenticationClientId
  urls:
    auth: https://${keycloak.domain}
